# Generated by Django 3.1 on 2020-09-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_ID', models.CharField(max_length=120)),
                ('emp_Name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('req_type', models.CharField(max_length=120)),
                ('user_req', models.CharField(max_length=120))
            ],
        ),
    ]
