# Generated by Django 2.1 on 2020-09-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_app', '0004_mvp_req_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mvp',
            name='req_ID',
        ),
    ]
