# Generated by Django 2.1 on 2020-09-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_app', '0005_remove_mvp_req_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MvpUserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Start_Date', models.CharField(max_length=100)),
                ('Start_Time', models.CharField(max_length=100)),
                ('End_Date', models.CharField(max_length=100)),
                ('End_Time', models.CharField(max_length=100)),
                ('Activity', models.CharField(max_length=100)),
                ('Mul_Over', models.CharField(max_length=100)),
                ('Timezone', models.CharField(max_length=100)),
                ('BreakTime', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
