# Generated by Django 2.1 on 2020-09-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp_app', '0006_mvpuserrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mvpuserrequest',
            name='Status',
            field=models.CharField(max_length=70),
        ),
    ]
